let message = {
    ru: {
        onlyLettersError: "----",

    },
    en: {
        onlyLettersError: "Insert only letters",
        onlyDigitsError: "Insert only digits",
        countDigitsError: "Length must be < ",
        trainExistError: "Train with this number already exists",
        incorrectDataError: "Inserted incorrect data",
        scheduleFormatError: "Incorrect format",
        scheduleDateError: "Incorrect date",
        details: "Details",
        return: "Return",
        haveNotUpcomingTrips: "You haven't upcoming trips",
        haveNotCompletedTrips: "You haven't completed trips",
        trainNumberSymbol: "№",
        from: "From",
        to: "To",
        departureDate: "Departure date",
        passengerHeader: "Passenger:",
        direct: "Direct",
        withTransfer: "With transfer",
        selectReturnTicket: "Select return ticket",
        buyTicket: "Buy ticket",
        trainNotFound: "Trains not found",
        arrivalDate: "Arrival date",
        numberOfTickets: "Number of tickets",
        trainNumberTrainModal: "Train number:",
        numberOfSeatsTrainModal: "Number of tickets:",
        stationsTrainModal: "Stations:",
        haveNotPassengers: "Haven't any passengers",
        passenger: "Passenger",
        birthDate: "Birth date",
        routeAddTrainModal: "Route:",
        trainNumberAddTrainModal: "Train number",
        ticketsAddTrainModal: "Number of tickets",
        addButtonAddTrainModal: "Add",
        userHaveNotPassengers: "You haven't any passengers",
        allOrdersButton: "All orders",
        adminRoles: "Roles",
        adminEditButton: "Edit"
    }
};